tutorial/accounts/urls.py
from django.urls import re_path
from . import view
from django.contrib.auth.views import login,logout,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
from django.urls import path

app_name="accounts"

urlpatterns = [
	path('',view.home, name='home'),
	path('login/',login,{'template_name': 'accounts/login.html'},name='login'),
	path('logout/',logout,{'template_name': 'accounts/logout.html'},name='logout'), 
	
	path('change_password/',view.change_password,name='change_password'),
	path('reset_password/',view.get_username, name='reset_password'),
	path('reset_password/<int:pk>/reset/',view.reset_password),
	# path('reset_password/',password_reset,{'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name':'accounts/reset_password_email.html'},name='reset_password'),
	
	# path('reset_password/done/',password_reset_done, {'template_name': 'accounts/reset_password_done.html'},name='password_reset_done'),
	# re_path(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,{'template_name': 'accounts/reset_password_confirm.html','post_reset_redirect':'accounts:password_reset_complete'},name='password_reset_confirm'),
	# path('reset_password/complete/',password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'},name='password_reset_complete'),

	path('Class/<int:year>/',view.ClassView, name='ClassView'),
	path('Class/<int:year>/<str:subject_name>/See All/',view.SeeAll,name = 'SeeAll'),
	path('Class/<int:year>/<str:subject_name>/<str:lesson_name>/',view.LessonView, name='LessonView'),
    
    path('Lessons/',view.teacher, name='Teachers'),
	path('Lessons/<int:pk>/edit/', view.ManageLessonView, name='Manage Lesson'),
	path('Lessons/add/', view.addContent, name='Create_lesson'),
    path('Lessons/<int:pk>/delete/', view.LessonDelete, name='Delete Lesson'),

	path('archive/add/', view.add_To_Archive, name='add_to_archive'),
	path('archive/SEF/<int:year>/', view.SEFArchive, name='SEFarchive'),
	path('archive/SEF/<int:year>/<str:subject_name>/', view.SEFArchiveSUB, name='SEFarchiveSUB'),
	path('archive/SEF/<int:year>/<str:subject_name>/<int:Set>/', view.SEFArchiveSUBSET, name='SEFarchiveSUBSET'),
	path('archive/WAEC/<str:subject_name>/', view.WAECArchive, name='WAECarchive'),
	
	path('archive/<str:PQ_Type>/', view.ArchiveView, name = 'archive'),
	
	
	path('contact/',view.contact,name='contact'),
	path('register/',view.student_register,name='student_register'),
	path('teacher_register/', view.teacher_register,name='teacher_register'),
	path('Choose_Subjects/', view.Choose_Subjects, name='choose_subject'),
	
	path('results/',view.search,name='search'),

	path('teacher_update/',view.TeacherUpdate, name='teacher_update'),
	path('student_update/',view.StudentUpdate, name='student_update'),
	#path('PastQuestions/',views.PQ,name='PQ'),
	
]

tutorial/spirit/core/tags/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from .registry import register


@register.simple_tag(takes_context=True)
def to_query_params(context, request=None, **params):
    """
    Adds params to current query string
    """
    # todo: use utils.to_query_params instead
    # todo: test!
    request = request or context['request']
    query_dict = request.GET.copy()  # MultiValueDict >___<

    for k, v in sorted(params.items()):
        query_dict[k] = v

    return query_dict.urlencode()

tutorial/spirit/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import include, url

import spirit.topic.views
import spirit.admin.urls
import spirit.user.urls
import spirit.search.urls
import spirit.category.urls
import spirit.topic.urls
import spirit.comment.urls


app_name = 'spirit'
urlpatterns = [
    url(r'^$', spirit.topic.views.index_active, name='index'),
    url(r'^st/admin/', include(spirit.admin.urls)),
    url(r'^user/', include(spirit.user.urls)),
    url(r'^search/', include(spirit.search.urls)),
    url(r'^category/', include(spirit.category.urls)),
    url(r'^topic/', include(spirit.topic.urls)),
    url(r'^comment/', include(spirit.comment.urls)),
	
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.contrib import admin 
from django.urls import path,include 
from tutorial import views

urlpatterns = [
	re_path(r'^forum/', include('spirit.urls')),
    path('',views.login_redirect,name='login_redirect'),#to go from without any / directly to login page
    path('admin/', admin.site.urls),
    path('home/',include('accounts.urls',namespace='accounts')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
	#path('search/', include('haystack.urls')),
] #+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone
from django.contrib import admin
from django.forms import CheckboxSelectMultiple
from django.db.models import Q
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class User(AbstractUser):
	is_teacher = models.BooleanField('Teacher Status', default = False)
	email = models.EmailField(blank =True)
	flogin = models.BooleanField(default = True) #first_login, but first_login is too long, 
	secret_question = models.CharField(max_length=50)
	secret_answer = models.CharField(max_length=10)



class Classe(models.Model):
	Year = models.IntegerField()

	def __str__(self):
		return str(self.Year)
	
class Subject(models.Model):
	name = models.CharField(max_length=50)
	Class = models.ForeignKey(Classe, on_delete = models.CASCADE)
	

	class Meta:
		ordering= ['name']
	
	def __str__(self):
		ans = self.name+ " "+ str(self.Class)
		return ans 
	
class Teacher(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	Subject7  = models.ManyToManyField(Subject, related_name='subjects_7', blank = True)
	Subject8 = models.ManyToManyField(Subject,related_name='subjects_8', blank = True)
	Subject9 = models.ManyToManyField(Subject, related_name='subjects_9', blank = True)
	Subject10 = models.ManyToManyField(Subject, related_name='subjects_10', blank = True)
	Subject11 = models.ManyToManyField(Subject, related_name='subjects_11', blank =True)
	Subject12 = models.ManyToManyField(Subject, related_name = 'subjects_12', blank  =True)
	

	
	def __str__(self):
		return str (self.user)
	
class Student(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	Class = models.ForeignKey(Classe, on_delete = models.CASCADE,null=True)
	Arm = models.CharField(max_length=1)
	Subject = models.ManyToManyField(Subject,blank=True)
	
	
	
	def __str__(self):
		return str (self.user)

class Lesson(models.Model):
	name  = models.CharField(max_length=150)
	description = RichTextUploadingField(max_length=100000,config_name='special',external_plugin_resources=[('youtube','/static/accounts/ckeditor_plugins/youtube/youtube/','plugin.js',)],blank=True ) 
	Teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE)
	document = models.FileField(blank=True,max_length=100000,upload_to='Lessons')
	subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)
	posted_A = models.BooleanField(default = False) 
	posted_B = models.BooleanField(default = False) 
	posted_C = models.BooleanField(default = False)	
	def __str__(self):
		return str (self.name)

	class Meta:
		ordering= ['-date']

	def get_absolute_url(self):
		return '/home/Class/'+str(self.subject.Class)+'/'+self.subject.name +'/'+self.name+'/'

class Contact(models.Model):
    name  = models.CharField(max_length=150)
    email = models.EmailField(max_length=70)
    subject = models.CharField(max_length=11)
    message = models.TextField() 
    
    def __str__(self):
    	return str(self.name)

class PastQuestion(models.Model):
	name = models.CharField(max_length=10, default='PQ')
	subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
	Set = models.IntegerField( null = True)
	Type = models.CharField(max_length=10) #The type of the PastQuestion 
	Exam_Type = models.CharField(max_length=10) #CA 1, CA 2 or other wise
	Term = models.CharField(max_length=10)
	document = models.FileField(upload_to='Past Questions')#remember to do the multiple file fields
	date = models.DateField(auto_now=True)

	class Meta:
		ordering = ['-date']

	def __str__(self):
		return str(self.name)	
	
class Email(models.Model):
	first_name = models.CharField(max_length =20,blank=True)
	last_name = models.CharField(max_length = 20,blank=True)
	email = models.EmailField(blank=True)
		
	def __str__(self):
		return self.email
class MyModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.ManyToManyField: {'widget': CheckboxSelectMultiple},
    }

	
	
@receiver(post_save, sender=User)
def create_or_update_teacher_or_user(sender, instance, created, **kwargs):
	
   if created and instance.is_teacher==True:
       Teacher.objects.create(user=instance)
       instance.teacher.save()
       
   elif created :
           Student.objects.create(user=instance)
           instance.student.save()

@receiver(post_save, sender=Email)
def email_create(sender, instance, created, **kwargs):
	if created:
#		instance.email = instance.first_name+'.'+instance.last_name+'@supremeeducation.com'
		instance.first_name= instance.email.split('.')[0]
		a=instance.email.split('.')[1]
		instance.last_name=a.split('@')[0]
		instance.save()           
			
#@receiver(post_save, sender=Student)
#def create_or_update_Student(sender, instance, created, **kwargs):
#	
#    if created :
#        student = instance
#        #stud_Class = Classe.objects.get(Year = student.Class)
#        subjects = Subject.objects.filter(Q(Class = student.Class) & Q(compulsory=True))
#        for subject in subjects:
#        	student.Subject.add(subject)
#        student.save()
#   #     teacher.save()
#		
#    #elif created and instance.is_teacher == False:
#     #       student = Student.objects.create(user=instance)
#      #      student.save()
			


            
            
   
	

tutorial/accounts/forms.py
from django import forms
from django.forms import ModelForm
from accounts.models import Lesson,Student,Contact,PastQuestion, Teacher,User,Subject
from django.forms.models import ModelMultipleChoiceField
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Classe as Classes

class addContentForm(ModelForm):
	class Meta:
		model = Lesson
		
		fields = ['name','subject','description','document','posted_A','posted_B','posted_C']

		
class CustomModelMultipleChoiceField(ModelMultipleChoiceField):
	def label_from_instance(self,obj):
		return "%s" % (obj.name)
	
	
class EditForm(ModelForm):
	class Meta:
		model = Student
		fields = ['Subject']
		field_classes ={
			'Subject':CustomModelMultipleChoiceField,
		}

		widgets = {
		'Subject': forms.CheckboxSelectMultiple()
		}

class ContactForm(ModelForm):

    class Meta:
    	model= Contact
    	fields =['subject','email','message']
		
class AddToArchiveForm(ModelForm):
	name = forms.CharField(required=True)
	class Meta:
		model = PastQuestion
		fields = '__all__'
		#widgets = {
		#'document': forms.FileInput(attrs={'id':'document'})
		#}

		

class StudentRegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)
	Class = forms.ModelChoiceField(required = True, queryset = Classes.objects.all())
	Arm = forms.CharField(max_length=1)
	class Meta:
		model = User
		fields = ['username', 'email','password1','password2', 'Class','Arm']


class TeacherRegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)
	class Meta:
		model = User
		fields = ['username', 'email','password1','password2']
class StudentUpdateForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2','secret_question','secret_answer']


class TeacherUpdateForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2','secret_question','secret_answer']

class GetUsernameForm(forms.Form):
	username = forms.CharField(max_length  = 10)

		

class CustomPasswordChangeForm(UserCreationForm):
	class Meta:
		model = User	
		fields = ['secret_answer','password1','password2']	

class ChooseSubjectsForm(ModelForm):
	class Meta:
		model = Teacher
		fields = ['Subject7', 'Subject8','Subject9','Subject10','Subject11','Subject12']
		field_classes={
		'Subject7':CustomModelMultipleChoiceField,
		'Subject8':CustomModelMultipleChoiceField,
		'Subject9':CustomModelMultipleChoiceField,
		'Subject10':CustomModelMultipleChoiceField,
		'Subject11':CustomModelMultipleChoiceField,
		'Subject12':CustomModelMultipleChoiceField
		}
		widgets = {
		'Subject7': forms.CheckboxSelectMultiple(),
		'Subject8': forms.CheckboxSelectMultiple(),
		'Subject9': forms.CheckboxSelectMultiple(),
		'Subject10': forms.CheckboxSelectMultiple(),
		'Subject11': forms.CheckboxSelectMultiple(),
		'Subject12': forms.CheckboxSelectMultiple()
		}
		labels = {
		'Subject7': 'Year 7',
		'Subject8': 'Year 8',
		'Subject9': 'Year 9',
		'Subject10': 'Year 10',
		'Subject11': 'Year 11',
		'Subject12': 'Year 12',	
		
		}

tutorial/accounts/views.py
from django.shortcuts import render

# Create your views here.

tutorial/accounts/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>SEF TUTOR</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,900" rel="stylesheet">
	  
    {%load static%}
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.css' %}">
<!--
	  <link rel="stylesheet" href="{% static 'accounts/css/bootstrapi.css' %}">
	  <link rel="stylesheet" href="{% static 'accounts/css/bootstrapi.min.css' %}">
	  <link rel="stylesheet" href="{% static 'accounts/css/bootstrap-themei.css' %}">
	  <link rel="stylesheet" href="{% static 'accounts/css/bootstrap-themei.min.css' %}">
-->
    <link rel="stylesheet" href="{% static 'accounts/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'accounts/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/fonts/flaticon/font/flaticon.css' %}">
 
    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
	  
	  {% block head %}
	  <section  data-stellar-background-ratio="0.5" style="background-image: url({% static 'accounts/images/big_image_1.jpg' %});">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
				<br>
				<br>
				<br>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
	  {% endblock %}
  </head>
	
  <body>
	  {% block header %}
	  
	  {% if user.is_authenticated %}
    <header role="banner">
     
      <nav class="navbar navbar-expand-md navbar-dark bglight">
        <div class="container">
          <a class="navbar-brand absolute" href="{% url 'accounts:home' %}">SEF tutor</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
			  
          </button>
                 
          <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
			  <form id="demo-2"action="/home/results/" method='GET'>
	               <input type="search" placeholder="Search" name = 'q' value = '{{request.GET.q}}'>

                </form>
             
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'accounts:home' %}">Home</a>
              </li>
				{% if user.is_teacher %}
				 <li class="nav-item">
                <a class="nav-link" href = '/home/Lessons'>Lessons</a>
              </li>
				{% else %}
				
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="courses.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Classes</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href="{% url 'accounts:ClassView' '7' %}">Year 7</a>
                  <a class="dropdown-item" href="{% url 'accounts:ClassView' '8' %}">Year 8</a>
                  <a class="dropdown-item" href="{% url 'accounts:ClassView' '9' %}">Year 9</a>
                  <a class="dropdown-item" href="{% url 'accounts:ClassView' '10' %}">Year 10</a>
                  <a class="dropdown-item" href="{% url 'accounts:ClassView' '11' %}">Year 11</a>
				  <a class="dropdown-item" href="{% url 'accounts:ClassView' '12' %}">Year 12</a>
                </div>

              </li>
                {% endif %}
				
                <li class="nav-item">
                <a class="nav-link" href="https://calendar.google.com/calendar/b/1?cid=c2VmdHV0b3IwQGdtYWlsLmNvbQ">Timeline</a>
              </li>
				{% if user.is_teacher %}
				
				<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="courses.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Archive</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
				  <a class="dropdown-item" href= "/home/archive/add">Add PastQuestion</a>	
                  <a class="dropdown-item" href= "/home/archive/SEF">SEF</a>
                  <a class="dropdown-item" href="/home/archive/WAEC/">WAEC</a>
                  <a class="dropdown-item" href="/home/archive/SAT/">SAT</a>
                  
                </div>

              </li>
				{% else %}
				 <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="courses.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Archive</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href= "/home/archive/SEF/">SEF</a>
                  <a class="dropdown-item" href="/home/archive/WAEC/">WAEC</a>
                  <a class="dropdown-item" href="/home/archive/SAT/">SAT</a>
                  
                </div>

              </li>
                {% endif %}
             
              <li class="nav-item">
                <a class="nav-link" href="/forum">Forum</a>
              </li>
<!--
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
-->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:contact' %}">Contact Us</a>
              </li>
            </ul>

            <ul class="navbar-nav absolute-right">  
				
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="courses.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome  {{ user.username }}</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
					{% if user.is_teacher %}
				  <a class="dropdown-item" href="{% url 'accounts:choose_subject' %}">Change Subjects</a>
					{% else %}
					{% endif %}
					{% if user.is_superuser %}
					<a class="dropdown-item" href="/admin/">Admin Page</a>
					{% else %}
					{% endif %}
					

<!--				  <a class="dropdown-item" href="#" data-toggle='modal' data-target='#ChangeAvatar'>Edit Profile</a>-->
<!--				<button class='dropdown-item' data-toggle='modal' data-target = '#EditProfileModal' type='button'>Edit</button>-->

                </div>
              </li>
                <li class="nav-item">
                <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
              </li>
				

            </ul>
  
          </div>
			
        </div>
		  
        
<!--
		  		<div class='modal fade' id='EditProfileModal'  role='dialog'>
	<div class='modal-dialog modal-dialog-centered" role='document''>
		<div class='modal-content'>
			<div class='modal-header'>
				<h5 class='modal-title'>Add Avatar</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>

			</div>
			<div class='modal-body'>
				 <form method='post'>
                   {% csrf_token %}
                   {{ form.non_field_errors }}
                   {{ form.image.errors }}
                   {{ form.image }}
             <div class="modal-footer">
           <button style="border-radius: 12px" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
           <button style="border-radius: 12px" type="submit" class="btn btn-primary">Save changes</button>
           </div>
                  </form>
			</div>
		</div>
	</div>
</div>
-->
      </nav>

    </header>
	  {% else %}
	 <header role="banner">
     
      <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <div class="container">
          <a class="navbar-brand absolute" href="{% url 'accounts:home' %}">SEF tutor</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
			  
          </button>
                 
          <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
			  <form id="demo-2"action="/home/results/" method='GET'>
	               <input type="search" placeholder="Search" name = 'q' value = '{{request.GET.q}}'>

                </form>
             
            
            <ul class="navbar-nav absolute-right">  
				
                <li class="nav-item">
                <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
              </li>
               <!-- <li class="nav-item">
                <a href="{% url 'accounts:student_register' %}" class="nav-link">Register</a>
              </li>-->
				

            </ul>
  
          </div>
			
        </div>
		
      </nav>

    </header>
	{%endif %}
    <!-- END header -->

	  {% endblock %}
	  
     {% block body %}
	  
    {% endblock %}
     
      
      
  {% block footer %}
	{% if user.is_authenticated %}
    <footer class="site-footer" style="background-image: url({% static 'accounts/images/big_image_3.jpg' %});">
       
        <div class="wrapper">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-4">
            <h3>About</h3>
            <p>SEF TUTOR is an web based online learning resource designed to improve your learning experience with the help of the latest technology.</p>
          </div>
          <div class="col-md-6 ml-auto">
            <div class="row">
              <div class="col-md-4">
                <ul class="list-unstyled">
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                </ul>
              </div>
              <div class="col-md-4">
                <ul class="list-unstyled">
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                </ul>
              </div>
              <div class="col-md-4">
                <ul class="list-unstyled">
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
            </div>
    </footer>
    <!-- END footer -->
          
	{% else %}
	
	{% endif %}
	  {% endblock %}
    
    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'accounts/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'accounts/js/jquery-migrate-3.0.0.js' %}"></script>
    <script src="{% static 'accounts/js/popper.min.js' %}"></script>
    <script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'accounts/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'accounts/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'accounts/js/jquery.stellar.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    
    <script src="{% static 'accounts/js/main.js' %}"></script>
      


  </body>
</html>